# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

before_install:
  - pip install --upgrade pip
  - pip install --upgrade wheel
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set show_channel_urls true
  - conda info --all  

install:
  - conda env create -n test_env --quiet --file ci/environment-py36.yml
  - source activate test_env
  - conda list
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source pystream -m pytest --verbose

after_success:
  - coverage report -m
  - coveralls

# deploy new versions to PyPI
deploy:
  provider: pypi
  on:
    tags: true
    python: 3.6
  user: martibosch
